name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps: 

    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

        run: |
                docker build . --file Dockerfile --tag ghcr.io/${{ github.repository }}:$(date +%m)
                docker push ghcr.io/${{ github.repository }}:$(date +%m)